# Generated by Django 6.0.2 on 2026-08-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('job_seeker', 'Job Seeker'), ('employer', 'Employer')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('unemployed', 'Unemployed'), ('employed', 'Employed')], default=None, max_length=20, null=True),
        ),
    ]
