# Generated by Django 6.0.2 on 2026-08-11 19:05

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_account_type_user_employment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenticationevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={},
        ),
        migrations.AlterField(
            model_name='authenticationevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authenticationevent',
            name='event_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_reset', 'Password Reset')], max_length=30),
        ),
        migrations.CreateModel(
            name='EmployerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_permit', models.FileField(blank=True, upload_to=accounts.models.employer_verification_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), accounts.models.validate_employer_document_size])),
                ('barangay_clearance', models.FileField(blank=True, upload_to=accounts.models.employer_verification_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), accounts.models.validate_employer_document_size])),
                ('mayors_permit', models.FileField(blank=True, upload_to=accounts.models.employer_verification_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), accounts.models.validate_employer_document_size])),
                ('cedula', models.FileField(blank=True, upload_to=accounts.models.employer_verification_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), accounts.models.validate_employer_document_size])),
                ('valid_id', models.FileField(blank=True, upload_to=accounts.models.employer_verification_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), accounts.models.validate_employer_document_size])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('access_accepted', 'Access Accepted'), ('access_denied', 'Access Denied')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employer Verification',
                'verbose_name_plural': 'Employer Verifications',
                'ordering': ['-updated_at'],
            },
        ),
    ]
